/// Token Compliance Audit — scans lib/ for forbidden patterns
/// Run: dart tool/token_compliance_audit.dart
/// Outputs markdown report to docs/TOKEN_COMPLIANCE_AUDIT.md
import 'dart:io';

void main() {
  final violations = <String, Map<String, int>>{};
  final patterns = <_Pattern>[
    _Pattern('GoogleFonts.lexend', RegExp(r'GoogleFonts\.lexend\('), 'high'),
    _Pattern('GoogleFonts.inter', RegExp(r'GoogleFonts\.inter\('), 'high'),
    _Pattern('Colors.white', RegExp(r'Colors\.white(?!\s*==)'), 'medium'),
    _Pattern('Colors.grey', RegExp(r'Colors\.grey'), 'medium'),
    _Pattern('Colors.black', RegExp(r'Colors\.black(?!\s*==)'), 'medium'),
    _Pattern('Color(0xFF', RegExp(r'Color\(0xFF'), 'medium'),
    _Pattern('BorderRadius.circular', RegExp(r'BorderRadius\.circular\('), 'low'),
    _Pattern('BoxShadow(', RegExp(r'BoxShadow\('), 'low'),
    _Pattern('EdgeInsets.all(', RegExp(r'EdgeInsets\.all\('), 'low'),
    _Pattern('EdgeInsets.only(', RegExp(r'EdgeInsets\.only\('), 'low'),
    _Pattern('EdgeInsets.fromLTRB(', RegExp(r'EdgeInsets\.fromLTRB\('), 'low'),
    _Pattern('EdgeInsets.symmetric(', RegExp(r'EdgeInsets\.symmetric\('), 'low'),
  ];

  final dir = Directory('lib');
  final files = dir.listSync(recursive: true).whereType<File>().toList();

  for (final file in files) {
    if (!file.path.endsWith('.dart')) continue;
    final content = file.readAsStringSync();
    final relativePath = file.path.replaceAll('\\', '/');

    for (final pattern in patterns) {
      final matches = pattern.regex.allMatches(content);
      if (matches.isNotEmpty) {
        violations.putIfAbsent(relativePath, () => {});
        violations[relativePath]![pattern.name] =
            (violations[relativePath]![pattern.name] ?? 0) + matches.length;
      }
    }
  }

  var report = '# Token Compliance Audit\n\n';
  report += 'Generated by `tool/token_compliance_audit.dart`\n\n';
  report += '## Summary\n\n';
  report += '| Pattern | Total Violations | Files Affected | Priority |\n';
  report += '|---|---|---|---|\n';

  final totals = <String, int>{};
  final affectedCount = <String, int>{};
  for (final file in violations.entries) {
    for (final pattern in file.value.entries) {
      totals[pattern.key] = (totals[pattern.key] ?? 0) + pattern.value;
      affectedCount[pattern.key] = (affectedCount[pattern.key] ?? 0) + 1;
    }
  }

  final priorityMap = <String, String>{};
  for (final p in patterns) {
    priorityMap[p.name] = p.priority;
  }

  for (final pattern in patterns.map((p) => p.name)) {
    final total = totals[pattern] ?? 0;
    final affected = affectedCount[pattern] ?? 0;
    report += '| `$pattern` | $total | $affected | ${priorityMap[pattern]} |\n';
  }

  report += '\n### Total Violations: ${totals.values.fold(0, (a, b) => a + b)}\n';
  report += '### Total Files: ${violations.length}\n\n';

  report += '## File Detail\n\n';
  report += '| File | ';
  for (final p in patterns.map((p) => p.name)) {
    report += '$p | ';
  }
  report += 'Total | Priority Score |\n|---|';
  for (final _ in patterns) {
    report += '---|';
  }
  report += '---|---|\n';

  final sortedFiles = violations.keys.toList()..sort();
  for (final file in sortedFiles) {
    final fileViolations = violations[file]!;
    int total = 0;
    int priorityScore = 0;
    report += '| `$file` | ';
    for (final pattern in patterns.map((p) => p.name)) {
      final count = fileViolations[pattern] ?? 0;
      report += '$count | ';
      total += count;
      if (count > 0) {
        switch (priorityMap[pattern]) {
          case 'high':
            priorityScore += count * 3;
            break;
          case 'medium':
            priorityScore += count * 2;
            break;
          default:
            priorityScore += count;
        }
      }
    }
    report += '$total | $priorityScore |\n';
  }

  report += '\n## Priority Legend\n\n';
  report += '- **High**: GoogleFonts usage — replace with AppTypography\n';
  report += '- **Medium**: Direct color usage — replace with AppColors\n';
  report += '- **Low**: Layout/style literals — replace with AppSpacing, AppBorderRadius, AppShadows\n';

  report += '\n---\n';
  report += '\n*Token compliance target: zero violations across all categories.*\n';

  File('docs/TOKEN_COMPLIANCE_AUDIT.md').writeAsStringSync(report);
  print('Compliance audit written to docs/TOKEN_COMPLIANCE_AUDIT.md');
  print('${violations.length} files with violations, ${totals.values.fold(0, (a, b) => a + b)} total patterns found.');
}

class _Pattern {
  final String name;
  final RegExp regex;
  final String priority;

  const _Pattern(this.name, this.regex, this.priority);
}
