/// UI Component Audit — scans screens for legacy widget usage
/// Run: dart tool/ui_component_audit.dart
/// Outputs markdown report to docs/UI_COMPONENT_AUDIT.md
import 'dart:io';

void main() {
  final screens = <String, Map<String, int>>{};
  final patterns = <String, Pattern>{
    'AppFlatRow(': RegExp(r'AppFlatRow\('),
    'AppFlatRowGroup(': RegExp(r'AppFlatRowGroup\('),
    'FinanceListRow(': RegExp(r'FinanceListRow\('),
    'ActivityListRow(': RegExp(r'ActivityListRow\('),
    'LinearStatBar(': RegExp(r'LinearStatBar\('),
    'FlatBackAppBar(': RegExp(r'FlatBackAppBar\('),
    'AppSectionHeader.': RegExp(r'AppSectionHeader\.'),
    'GameRow(': RegExp(r'GameRow\('),
    'RowGroup(': RegExp(r'RowGroup\('),
    'SectionLabel(': RegExp(r'SectionLabel\('),
    'StatBar(': RegExp(r'StatBar\('),
    'BondBar(': RegExp(r'BondBar\('),
    'Colors.white': RegExp(r'Colors\.white'),
    'Colors.grey': RegExp(r'Colors\.grey'),
    'GoogleFonts.lexend': RegExp(r'GoogleFonts\.lexend\('),
    'GoogleFonts.inter': RegExp(r'GoogleFonts\.inter\('),
    'EdgeInsets.all': RegExp(r'EdgeInsets\.all\([1-9]'),
    'EdgeInsets.symmetric': RegExp(r'EdgeInsets\.symmetric\(horizontal'),
    'BorderRadius.circular': RegExp(r'BorderRadius\.circular\([1-9]'),
    'BoxShadow(': RegExp(r'BoxShadow\('),
  };

  final dir = Directory('lib/screens');
  final files = dir.listSync(recursive: true).whereType<File>().toList();

  for (final file in files) {
    if (!file.path.endsWith('.dart')) continue;
    final content = file.readAsStringSync();
    final relativePath = file.path.replaceAll('\\', '/');
    final screenName = relativePath.replaceFirst('lib/screens/', '');

    for (final entry in patterns.entries) {
      final matches = entry.value.allMatches(content);
      if (matches.isNotEmpty) {
        screens.putIfAbsent(relativePath, () => {});
        screens[relativePath]![entry.key] =
            (screens[relativePath]![entry.key] ?? 0) + matches.length;
      }
    }
  }

  // Generate Markdown
  var report = '# UI Component Audit\n\n';
  report += 'Generated by `tool/ui_component_audit.dart`\n\n';
  report += '## Pattern Summary\n\n';
  report += '| Pattern | Total Occurrences | Screens Affected |\n';
  report += '|---|---|---|\n';

  final totals = <String, int>{};
  final affectedCount = <String, int>{};
  for (final screen in screens.entries) {
    for (final pattern in screen.value.entries) {
      totals[pattern.key] = (totals[pattern.key] ?? 0) + pattern.value;
      affectedCount[pattern.key] = (affectedCount[pattern.key] ?? 0) + 1;
    }
  }
  for (final pattern in totals.keys) {
    report += '| `$pattern` | ${totals[pattern]} | ${affectedCount[pattern]} |\n';
  }

  report += '\n## Screen Detail\n\n';
  report += '| Screen | ';
  for (final key in patterns.keys) {
    report += '$key | ';
  }
  report += '|\n|---|';
  for (final _ in patterns.keys) {
    report += '---|';
  }
  report += '\n';

  final sortedScreens = screens.keys.toList()..sort();
  for (final screen in sortedScreens) {
    report += '| `$screen` | ';
    for (final patternName in patterns.keys) {
      final count = screens[screen]?[patternName];
      report += '${count ?? 0} | ';
    }
    report += '\n';
  }

  report += '\n## Migration Priority\n\n';
  report += 'Based on legacy widget count:\n\n';
  final sortedByTotal = screens.entries.toList()
    ..sort((a, b) =>
        b.value.values.fold(0, (s, v) => s + v) -
        a.value.values.fold(0, (s, v) => s + v));
  for (int i = 0; i < sortedByTotal.length; i++) {
    final screen = sortedByTotal[i];
    final total = screen.value.values.fold(0, (s, v) => s + v);
    report += '${i + 1}. `$screen` — $total legacy patterns\n';
  }

  File('docs/UI_COMPONENT_AUDIT.md').writeAsStringSync(report);
  print('Audit written to docs/UI_COMPONENT_AUDIT.md');
  print('${screens.length} screens scanned, ${totals.values.fold(0, (s, v) => s + v)} legacy patterns found.');
}
