// lib/core/career_data.dart


enum CareerTier { low, mid, high, elite, freelance, partTime, special, fullTime }

enum Industry { tech, medical, govt, creative, commerce, services, manual }

class JobDefinition {
  final String title;
  final Industry industry;
  final CareerTier tier;
  final double startingSalary;
  final int stressLevel; // 0-100
  final double growthRate; // multiplier for salary increases
  final int smartsReq;
  final int socialReq;
  final String eduReq;
  final String? specializationReq;
  final String? examReq; // e.g. 'UPSC', 'SSC', 'BankPO' — requires passed_<examReq> memory flag
  final String emoji;
  final String description;
  final String? lockReason; // Shown in UI when job is locked

  const JobDefinition({
    required this.title,
    required this.industry,
    required this.tier,
    required this.startingSalary,
    required this.stressLevel,
    required this.growthRate,
    required this.smartsReq,
    required this.socialReq,
    required this.eduReq,
    this.specializationReq,
    this.examReq,
    this.lockReason,
    required this.emoji,
    required this.description,
  });
}

class CareerData {
  static const List<JobDefinition> allJobs = [
    // ── Low Tier / Entry Level ──
    JobDefinition(
      title: 'Delivery Partner',
      industry: Industry.services,
      tier: CareerTier.low,
      startingSalary: 120000,
      stressLevel: 40,
      growthRate: 1.05,
      smartsReq: 10,
      socialReq: 30,
      eduReq: 'None',
      emoji: '🛵',
      description: 'Deliver food and packages across the city.',
    ),
    JobDefinition(
      title: 'Security Guard',
      industry: Industry.services,
      tier: CareerTier.low,
      startingSalary: 144000,
      stressLevel: 30,
      growthRate: 1.03,
      smartsReq: 20,
      socialReq: 20,
      eduReq: 'None',
      emoji: '💂',
      description: 'Guard residential or commercial properties.',
    ),
    JobDefinition(
      title: 'Rickshaw Driver',
      industry: Industry.services,
      tier: CareerTier.low,
      startingSalary: 180000,
      stressLevel: 50,
      growthRate: 1.02,
      smartsReq: 15,
      socialReq: 40,
      eduReq: 'None',
      emoji: '🛺',
      description: 'Ferrying passengers through city traffic.',
    ),
    JobDefinition(
      title: 'Construction Worker',
      industry: Industry.manual,
      tier: CareerTier.low,
      startingSalary: 150000,
      stressLevel: 60,
      growthRate: 1.04,
      smartsReq: 10,
      socialReq: 20,
      eduReq: 'None',
      emoji: '🏗️',
      description: 'Physical labor on building sites.',
    ),
    JobDefinition(
      title: 'Dhaba Assistant',
      industry: Industry.services,
      tier: CareerTier.low,
      startingSalary: 96000,
      stressLevel: 55,
      growthRate: 1.03,
      smartsReq: 5,
      socialReq: 25,
      eduReq: 'None',
      emoji: '🍛',
      description: 'Helping out in a busy roadside eatery.',
    ),
    JobDefinition(
      title: 'Field Labourer',
      industry: Industry.manual,
      tier: CareerTier.low,
      startingSalary: 84000,
      stressLevel: 65,
      growthRate: 1.02,
      smartsReq: 5,
      socialReq: 15,
      eduReq: 'None',
      emoji: '🌾',
      description: 'Working in agricultural fields during harvests.',
    ),
    JobDefinition(
      title: 'Courier Runner',
      industry: Industry.services,
      tier: CareerTier.low,
      startingSalary: 108000,
      stressLevel: 45,
      growthRate: 1.04,
      smartsReq: 15,
      socialReq: 30,
      eduReq: 'Primary',
      emoji: '📦',
      description: 'Walking or cycling to deliver letters and small parcels.',
    ),

    // ── Mid Tier ──
    JobDefinition(
      title: 'School Teacher',
      industry: Industry.govt,
      tier: CareerTier.mid,
      startingSalary: 360000,
      stressLevel: 45,
      growthRate: 1.1,
      smartsReq: 55,
      socialReq: 60,
      eduReq: 'Graduate',
      emoji: '👩‍🏫',
      description: 'Educating the next generation.',
    ),
    JobDefinition(
      title: 'Bank Clerk',
      industry: Industry.commerce,
      tier: CareerTier.mid,
      startingSalary: 420000,
      stressLevel: 40,
      growthRate: 1.12,
      smartsReq: 60,
      socialReq: 50,
      eduReq: 'Graduate',
      specializationReq: 'Commerce',
      emoji: '🏦',
      description: 'Handling transactions at a bank branch.',
    ),
    JobDefinition(
      title: 'Sales Executive',
      industry: Industry.commerce,
      tier: CareerTier.mid,
      startingSalary: 300000,
      stressLevel: 65,
      growthRate: 1.25,
      smartsReq: 40,
      socialReq: 75,
      eduReq: 'Higher Secondary',
      emoji: '💼',
      description: 'Meeting targets and closing deals.',
    ),
    JobDefinition(
      title: 'Junior Developer',
      industry: Industry.tech,
      tier: CareerTier.mid,
      startingSalary: 500000,
      stressLevel: 55,
      growthRate: 1.3,
      smartsReq: 65,
      socialReq: 30,
      eduReq: 'Graduate',
      specializationReq: 'PCM',
      emoji: '👨‍💻',
      description: 'Writing code for software products.',
    ),
    JobDefinition(
      title: 'Nursing Assistant',
      industry: Industry.medical,
      tier: CareerTier.mid,
      startingSalary: 240000,
      stressLevel: 70,
      growthRate: 1.08,
      smartsReq: 50,
      socialReq: 65,
      eduReq: 'Higher Secondary',
      specializationReq: 'PCB',
      emoji: '🏥',
      description: 'Helping patients in a hospital setup.',
    ),
    JobDefinition(
      title: 'BPO Executive',
      industry: Industry.tech,
      tier: CareerTier.mid,
      startingSalary: 240000,
      stressLevel: 75,
      growthRate: 1.15,
      smartsReq: 45,
      socialReq: 70,
      eduReq: 'Graduate',
      emoji: '🎧',
      description: 'Providing customer support over call/chat.',
    ),
    JobDefinition(
      title: 'Retail Store Manager',
      industry: Industry.commerce,
      tier: CareerTier.mid,
      startingSalary: 360000,
      stressLevel: 60,
      growthRate: 1.2,
      smartsReq: 50,
      socialReq: 70,
      eduReq: 'Graduate',
      emoji: '🛒',
      description: 'Managing operations and sales at a retail outlet.',
    ),
    JobDefinition(
      title: 'HR Coordinator',
      industry: Industry.commerce,
      tier: CareerTier.mid,
      startingSalary: 400000,
      stressLevel: 45,
      growthRate: 1.18,
      smartsReq: 55,
      socialReq: 80,
      eduReq: 'Graduate',
      emoji: '🤝',
      description: 'Handling recruitment and employee relations.',
    ),
    JobDefinition(
      title: 'Digital Marketer',
      industry: Industry.creative,
      tier: CareerTier.mid,
      startingSalary: 420000,
      stressLevel: 50,
      growthRate: 1.3,
      smartsReq: 60,
      socialReq: 65,
      eduReq: 'Graduate',
      emoji: '📱',
      description: 'Managing social media and online ads.',
    ),
    JobDefinition(
      title: 'Data Analyst',
      industry: Industry.tech,
      tier: CareerTier.mid,
      startingSalary: 600000,
      stressLevel: 55,
      growthRate: 1.25,
      smartsReq: 75,
      socialReq: 40,
      eduReq: 'Graduate',
      specializationReq: 'PCM',
      emoji: '📊',
      description: 'Interpreting complex data to help businesses.',
    ),
    JobDefinition(
      title: 'Junior Architect',
      industry: Industry.tech,
      tier: CareerTier.mid,
      startingSalary: 480000,
      stressLevel: 65,
      growthRate: 1.2,
      smartsReq: 70,
      socialReq: 55,
      eduReq: 'Graduate',
      specializationReq: 'PCM',
      emoji: '📐',
      description: 'Designing buildings and structural floor plans.',
    ),
    JobDefinition(
      title: 'Graphic Artist',
      industry: Industry.creative,
      tier: CareerTier.mid,
      startingSalary: 384000,
      stressLevel: 40,
      growthRate: 1.22,
      smartsReq: 50,
      socialReq: 55,
      eduReq: 'Graduate',
      emoji: '🎨',
      description: 'Creating visual art and commercial designs.',
    ),
    JobDefinition(
      title: 'Railway Ticket Collector',
      industry: Industry.govt,
      tier: CareerTier.mid,
      startingSalary: 300000,
      stressLevel: 55,
      growthRate: 1.08,
      smartsReq: 40,
      socialReq: 65,
      eduReq: 'Secondary',
      emoji: '🎫',
      description: 'Checking tickets on Indian Railways.',
    ),
    JobDefinition(
      title: 'Police Constable',
      industry: Industry.govt,
      tier: CareerTier.mid,
      startingSalary: 324000,
      stressLevel: 80,
      growthRate: 1.07,
      smartsReq: 40,
      socialReq: 60,
      eduReq: 'Secondary',
      emoji: '👮',
      description: 'Maintaining law and order on the streets.',
    ),
    JobDefinition(
      title: 'Journalist',
      industry: Industry.creative,
      tier: CareerTier.mid,
      startingSalary: 300000,
      stressLevel: 75,
      growthRate: 1.15,
      smartsReq: 65,
      socialReq: 85,
      eduReq: 'Graduate',
      emoji: '🎤',
      description: 'Reporting news and investigation stories.',
    ),

    // ── 10th Pass Extras ──
    JobDefinition(
      title: 'Factory Worker',
      industry: Industry.manual,
      tier: CareerTier.low,
      startingSalary: 132000,
      stressLevel: 60,
      growthRate: 1.03,
      smartsReq: 10,
      socialReq: 15,
      eduReq: 'Secondary',
      emoji: '🔧',
      description: 'Assembly line work in a manufacturing plant.',
      lockReason: 'Requires 10th pass',
    ),
    JobDefinition(
      title: 'Shop Assistant',
      industry: Industry.services,
      tier: CareerTier.low,
      startingSalary: 108000,
      stressLevel: 35,
      growthRate: 1.04,
      smartsReq: 15,
      socialReq: 45,
      eduReq: 'Secondary',
      emoji: '🏪',
      description: 'Helping customers and managing stock at a local shop.',
      lockReason: 'Requires 10th pass',
    ),
    // ── 12th Pass ──
    JobDefinition(
      title: 'Call Center Agent',
      industry: Industry.services,
      tier: CareerTier.mid,
      startingSalary: 216000,
      stressLevel: 65,
      growthRate: 1.1,
      smartsReq: 30,
      socialReq: 70,
      eduReq: 'Higher Secondary',
      emoji: '📞',
      description: 'Handling inbound customer queries round the clock.',
      lockReason: 'Requires 12th pass',
    ),
    JobDefinition(
      title: 'Railway Assistant',
      industry: Industry.govt,
      tier: CareerTier.mid,
      startingSalary: 264000,
      stressLevel: 50,
      growthRate: 1.08,
      smartsReq: 35,
      socialReq: 40,
      eduReq: 'Higher Secondary',
      emoji: '🚂',
      description: 'Station duties and passenger assistance on Indian Railways.',
      lockReason: 'Requires 12th pass',
    ),
    JobDefinition(
      title: 'Army Soldier',
      industry: Industry.govt,
      tier: CareerTier.mid,
      startingSalary: 300000,
      stressLevel: 90,
      growthRate: 1.07,
      smartsReq: 40,
      socialReq: 50,
      eduReq: 'Higher Secondary',
      emoji: '🪖',
      description: 'Serving the nation in the Indian Army.',
      lockReason: 'Requires 12th pass',
    ),
    // ── Graduate Professional ──
    JobDefinition(
      title: 'HR Associate',
      industry: Industry.commerce,
      tier: CareerTier.mid,
      startingSalary: 360000,
      stressLevel: 40,
      growthRate: 1.15,
      smartsReq: 50,
      socialReq: 75,
      eduReq: 'Graduate',
      emoji: '🤝',
      description: 'Supporting talent acquisition and employee operations.',
    ),
    JobDefinition(
      title: 'Lab Technician',
      industry: Industry.medical,
      tier: CareerTier.mid,
      startingSalary: 300000,
      stressLevel: 55,
      growthRate: 1.1,
      smartsReq: 55,
      socialReq: 40,
      eduReq: 'Graduate',
      specializationReq: 'PCB',
      emoji: '🔬',
      description: 'Conducting medical tests and lab diagnostics.',
      lockReason: 'Requires PCB + Graduation',
    ),
    JobDefinition(
      title: 'Lawyer (Junior)',
      industry: Industry.creative,
      tier: CareerTier.mid,
      startingSalary: 480000,
      stressLevel: 70,
      growthRate: 1.2,
      smartsReq: 70,
      socialReq: 65,
      eduReq: 'Graduate',
      specializationReq: 'Arts',
      emoji: '⚖️',
      description: 'Practicing law at a district court.',
      lockReason: 'Requires Arts/Law graduation',
    ),
    JobDefinition(
      title: 'Professor',
      industry: Industry.govt,
      tier: CareerTier.mid,
      startingSalary: 720000,
      stressLevel: 40,
      growthRate: 1.12,
      smartsReq: 80,
      socialReq: 65,
      eduReq: 'Postgraduate',
      emoji: '📖',
      description: 'Teaching undergraduates at a government college.',
    ),
    // ── Government Exam Gated ──
    JobDefinition(
      title: 'IAS Officer',
      industry: Industry.govt,
      tier: CareerTier.high,
      startingSalary: 1200000,
      stressLevel: 80,
      growthRate: 1.15,
      smartsReq: 90,
      socialReq: 80,
      eduReq: 'Graduate',
      examReq: 'UPSC',
      emoji: '🏛️',
      description: 'High-level district administration for the Government of India.',
      lockReason: 'Requires UPSC clearance',
    ),
    JobDefinition(
      title: 'IPS Officer',
      industry: Industry.govt,
      tier: CareerTier.high,
      startingSalary: 1080000,
      stressLevel: 85,
      growthRate: 1.12,
      smartsReq: 88,
      socialReq: 82,
      eduReq: 'Graduate',
      examReq: 'UPSC',
      emoji: '🚔',
      description: 'Leading police operations across India.',
      lockReason: 'Requires UPSC clearance',
    ),
    JobDefinition(
      title: 'IFS Officer',
      industry: Industry.govt,
      tier: CareerTier.high,
      startingSalary: 1080000,
      stressLevel: 70,
      growthRate: 1.1,
      smartsReq: 87,
      socialReq: 85,
      eduReq: 'Graduate',
      examReq: 'UPSC',
      emoji: '🌐',
      description: 'Representing India in foreign missions and embassies.',
      lockReason: 'Requires UPSC clearance',
    ),
    JobDefinition(
      title: 'SSC Staff Selection Officer',
      industry: Industry.govt,
      tier: CareerTier.mid,
      startingSalary: 480000,
      stressLevel: 50,
      growthRate: 1.1,
      smartsReq: 60,
      socialReq: 50,
      eduReq: 'Graduate',
      examReq: 'SSC',
      emoji: '📋',
      description: 'Central government clerical and officer-grade post.',
      lockReason: 'Requires SSC clearance',
    ),
    JobDefinition(
      title: 'Bank PO',
      industry: Industry.commerce,
      tier: CareerTier.mid,
      startingSalary: 600000,
      stressLevel: 55,
      growthRate: 1.15,
      smartsReq: 65,
      socialReq: 55,
      eduReq: 'Graduate',
      examReq: 'BankPO',
      emoji: '🏦',
      description: 'Probationary Officer at a nationalised bank.',
      lockReason: 'Requires Bank PO exam clearance',
    ),
    JobDefinition(
      title: 'RBI Grade B Officer',
      industry: Industry.commerce,
      tier: CareerTier.high,
      startingSalary: 900000,
      stressLevel: 65,
      growthRate: 1.18,
      smartsReq: 85,
      socialReq: 60,
      eduReq: 'Graduate',
      examReq: 'BankPO',
      emoji: '🏛️',
      description: 'Officer at the Reserve Bank of India.',
      lockReason: 'Requires Bank PO exam clearance',
    ),
    JobDefinition(
      title: 'PSU Engineer',
      industry: Industry.govt,
      tier: CareerTier.high,
      startingSalary: 840000,
      stressLevel: 55,
      growthRate: 1.12,
      smartsReq: 80,
      socialReq: 45,
      eduReq: 'Graduate',
      specializationReq: 'PCM',
      examReq: 'SSC',
      emoji: '⚙️',
      description: 'Engineer at BHEL, NTPC, ONGC or similar PSU.',
      lockReason: 'Requires PCM degree + SSC-JE clearance',
    ),
    // ── High Tier ──
    JobDefinition(
      title: 'Software Architect',
      industry: Industry.tech,
      tier: CareerTier.high,
      startingSalary: 2400000,
      stressLevel: 60,
      growthRate: 1.2,
      smartsReq: 85,
      socialReq: 50,
      eduReq: 'Postgraduate',
      specializationReq: 'PCM',
      emoji: '🏗️',
      description: 'Designing large scale software systems.',
    ),
    JobDefinition(
      title: 'IAS Officer',
      industry: Industry.govt,
      tier: CareerTier.high,
      startingSalary: 1200000,
      stressLevel: 80,
      growthRate: 1.15,
      smartsReq: 90,
      socialReq: 80,
      eduReq: 'Graduate',
      emoji: '🏛️',
      description: 'High-level administration for the country.',
    ),
    JobDefinition(
      title: 'Chartered Accountant',
      industry: Industry.commerce,
      tier: CareerTier.high,
      startingSalary: 1500000,
      stressLevel: 75,
      growthRate: 1.18,
      smartsReq: 85,
      socialReq: 60,
      eduReq: 'Postgraduate',
      specializationReq: 'Commerce',
      emoji: '⚖️',
      description: 'Expert in finance, audit, and tax.',
    ),
    JobDefinition(
      title: 'Specialist Doctor',
      industry: Industry.medical,
      tier: CareerTier.high,
      startingSalary: 1800000,
      stressLevel: 85,
      growthRate: 1.2,
      smartsReq: 95,
      socialReq: 70,
      eduReq: 'Postgraduate',
      specializationReq: 'PCB',
      emoji: '👨‍⚕️',
      description: 'Expert medical practitioner.',
    ),
    JobDefinition(
      title: 'Senior Corporate Lawyer',
      industry: Industry.commerce,
      tier: CareerTier.high,
      startingSalary: 2000000,
      stressLevel: 80,
      growthRate: 1.22,
      smartsReq: 88,
      socialReq: 85,
      eduReq: 'Postgraduate',
      specializationReq: 'Arts',
      emoji: '⚖️',
      description: 'Handling high-stakes legal matters for firms.',
    ),
    JobDefinition(
      title: 'Investment Banker',
      industry: Industry.commerce,
      tier: CareerTier.high,
      startingSalary: 2400000,
      stressLevel: 90,
      growthRate: 1.3,
      smartsReq: 92,
      socialReq: 85,
      eduReq: 'Postgraduate',
      specializationReq: 'Commerce',
      emoji: '💹',
      description: 'Raising capital and advising on M&A.',
    ),
    JobDefinition(
      title: 'Machine Learning Engineer',
      industry: Industry.tech,
      tier: CareerTier.high,
      startingSalary: 2800000,
      stressLevel: 70,
      growthRate: 1.35,
      smartsReq: 94,
      socialReq: 40,
      eduReq: 'Postgraduate',
      specializationReq: 'PCM',
      emoji: '🤖',
      description: 'Building advanced AI and predictive models.',
    ),
    JobDefinition(
      title: 'ISRO Scientist',
      industry: Industry.govt,
      tier: CareerTier.high,
      startingSalary: 1080000,
      stressLevel: 55,
      growthRate: 1.1,
      smartsReq: 95,
      socialReq: 50,
      eduReq: 'Postgraduate',
      specializationReq: 'PCM',
      emoji: '🚀',
      description: 'Conducting space research and rocket launches.',
    ),
    JobDefinition(
      title: 'Commercial Pilot',
      industry: Industry.services,
      tier: CareerTier.high,
      startingSalary: 3600000,
      stressLevel: 80,
      growthRate: 1.12,
      smartsReq: 85,
      socialReq: 75,
      eduReq: 'Higher Secondary',
      emoji: '👩‍✈️',
      description: 'Flying passenger jets across the globe.',
    ),
    JobDefinition(
      title: 'Architectural Designer',
      industry: Industry.manual,
      tier: CareerTier.high,
      startingSalary: 1200000,
      stressLevel: 65,
      growthRate: 1.2,
      smartsReq: 80,
      socialReq: 70,
      eduReq: 'Graduate',
      emoji: '🏠',
      description: 'Leading building projects from vision to reality.',
    ),

    // ── Elite Tier ──
    JobDefinition(
      title: 'CEO',
      industry: Industry.commerce,
      tier: CareerTier.elite,
      startingSalary: 6000000,
      stressLevel: 95,
      growthRate: 1.5,
      smartsReq: 90,
      socialReq: 95,
      eduReq: 'Postgraduate',
      emoji: '👑',
      description: 'Leading a major corporation.',
    ),
    JobDefinition(
      title: 'Supreme Court Lawyer',
      industry: Industry.creative,
      tier: CareerTier.elite,
      startingSalary: 4800000,
      stressLevel: 90,
      growthRate: 1.4,
      smartsReq: 95,
      socialReq: 90,
      eduReq: 'Postgraduate',
      emoji: '🏛️',
      description: 'Top tier legal representative.',
    ),
    JobDefinition(
      title: 'Tech Unicorn Founder',
      industry: Industry.tech,
      tier: CareerTier.elite,
      startingSalary: 10000000,
      stressLevel: 100,
      growthRate: 2.0,
      smartsReq: 95,
      socialReq: 95,
      eduReq: 'Graduate',
      emoji: '🦄',
      description: 'Building a billion-dollar company.',
    ),
    JobDefinition(
      title: 'Bollywood Superstar',
      industry: Industry.creative,
      tier: CareerTier.elite,
      startingSalary: 24000000,
      stressLevel: 85,
      growthRate: 1.8,
      smartsReq: 40,
      socialReq: 100,
      eduReq: 'Secondary',
      emoji: '🎬',
      description: 'Global fame and box office domination.',
    ),
    JobDefinition(
      title: 'Cricket Icon',
      industry: Industry.creative,
      tier: CareerTier.elite,
      startingSalary: 18000000,
      stressLevel: 90,
      growthRate: 1.6,
      smartsReq: 30,
      socialReq: 90,
      eduReq: 'Secondary',
      emoji: '🏏',
      description: 'National hero and master of the game.',
    ),
    JobDefinition(
      title: 'Global Hedge Fund Manager',
      industry: Industry.commerce,
      tier: CareerTier.elite,
      startingSalary: 12000000,
      stressLevel: 98,
      growthRate: 2.2,
      smartsReq: 98,
      socialReq: 80,
      eduReq: 'Postgraduate',
      specializationReq: 'Commerce',
      emoji: '📈',
      description: 'Managing billions in international capital.',
    ),
    JobDefinition(
      title: 'Chief Cabinet Secretary',
      industry: Industry.govt,
      tier: CareerTier.elite,
      startingSalary: 3000000,
      stressLevel: 95,
      growthRate: 1.2,
      smartsReq: 96,
      socialReq: 96,
      eduReq: 'Postgraduate',
      emoji: '🇮🇳',
      description: 'Highest ranking civil servant in the nation.',
    ),
  ];

  static const List<JobDefinition> freelancingRoles = [
    JobDefinition(
      title: 'Video Editor',
      industry: Industry.creative,
      tier: CareerTier.freelance,
      startingSalary: 50000,
      stressLevel: 40,
      growthRate: 1.5,
      smartsReq: 40,
      socialReq: 50,
      eduReq: 'None',
      emoji: '🎬',
      description: 'Edit videos for clients and creators.',
    ),
    JobDefinition(
      title: 'Web Developer',
      industry: Industry.tech,
      tier: CareerTier.freelance,
      startingSalary: 80000,
      stressLevel: 50,
      growthRate: 1.6,
      smartsReq: 60,
      socialReq: 40,
      eduReq: 'None',
      emoji: '🌐',
      description: 'Build websites and apps remotely.',
    ),
    JobDefinition(
      title: 'Graphic Designer',
      industry: Industry.creative,
      tier: CareerTier.freelance,
      startingSalary: 40000,
      stressLevel: 35,
      growthRate: 1.4,
      smartsReq: 45,
      socialReq: 55,
      eduReq: 'None',
      emoji: '🎨',
      description: 'Create visual identities and designs.',
    ),
    JobDefinition(
      title: 'Content Writer',
      industry: Industry.creative,
      tier: CareerTier.freelance,
      startingSalary: 30000,
      stressLevel: 30,
      growthRate: 1.3,
      smartsReq: 50,
      socialReq: 40,
      eduReq: 'Secondary',
      emoji: '✍️',
      description: 'Write articles, blogs, and copy for clients.',
    ),
    JobDefinition(
      title: 'Social Media Manager',
      industry: Industry.commerce,
      tier: CareerTier.freelance,
      startingSalary: 45000,
      stressLevel: 45,
      growthRate: 1.4,
      smartsReq: 40,
      socialReq: 70,
      eduReq: 'Secondary',
      emoji: '📱',
      description: 'Manage brand presence on social platforms.',
    ),
    JobDefinition(
      title: 'UI/UX Designer',
      industry: Industry.tech,
      tier: CareerTier.freelance,
      startingSalary: 70000,
      stressLevel: 40,
      growthRate: 1.5,
      smartsReq: 55,
      socialReq: 50,
      eduReq: 'Higher Secondary',
      emoji: '🎨',
      description: 'Design user interfaces and experiences.',
    ),
    JobDefinition(
      title: 'Digital Marketer',
      industry: Industry.commerce,
      tier: CareerTier.freelance,
      startingSalary: 55000,
      stressLevel: 50,
      growthRate: 1.4,
      smartsReq: 45,
      socialReq: 60,
      eduReq: 'Secondary',
      emoji: '📢',
      description: 'Promote products and services online.',
    ),
    JobDefinition(
      title: 'SEO Expert',
      industry: Industry.tech,
      tier: CareerTier.freelance,
      startingSalary: 60000,
      stressLevel: 35,
      growthRate: 1.4,
      smartsReq: 50,
      socialReq: 40,
      eduReq: 'Higher Secondary',
      emoji: '🔍',
      description: 'Optimize websites for search engines.',
    ),
    JobDefinition(
      title: 'Data Analyst',
      industry: Industry.tech,
      tier: CareerTier.freelance,
      startingSalary: 75000,
      stressLevel: 45,
      growthRate: 1.5,
      smartsReq: 70,
      socialReq: 30,
      eduReq: 'Graduate',
      emoji: '📊',
      description: 'Analyze data to provide business insights.',
    ),
    JobDefinition(
      title: 'Virtual Assistant',
      industry: Industry.services,
      tier: CareerTier.freelance,
      startingSalary: 25000,
      stressLevel: 30,
      growthRate: 1.2,
      smartsReq: 35,
      socialReq: 65,
      eduReq: 'Primary',
      emoji: '📧',
      description: 'Provide administrative support remotely.',
    ),
  ];
}
