import '../models/character.dart';
import '../models/part_time_job.dart';

class PartTimeJobsData {
  static const List<PartTimeJob> jobs = [
    PartTimeJob(
      id: 'grocery_helper',
      name: 'Grocery Store Helper',
      emoji: '🛒',
      minAge: 14,
      salary: 2500,
      hoursPerWeek: 10,
      responsibilityRequired: 0,
      experienceRequired: 0,
      stressGain: 4,
      experienceGain: 4,
      customerSkillGain: 2,
    ),
    PartTimeJob(
      id: 'barista_apprentice',
      name: 'Barista Apprentice',
      emoji: '☕',
      minAge: 16,
      salary: 3200,
      hoursPerWeek: 15,
      responsibilityRequired: 0,
      experienceRequired: 0,
      stressGain: 6,
      experienceGain: 5,
      customerSkillGain: 4,
    ),
    PartTimeJob(
      id: 'warehouse_sorter',
      name: 'Warehouse Sorter',
      emoji: '📦',
      minAge: 18,
      salary: 5000,
      hoursPerWeek: 18,
      responsibilityRequired: 0,
      experienceRequired: 10,
      stressGain: 8,
      experienceGain: 6,
      customerSkillGain: 1,
    ),
    PartTimeJob(
      id: 'library_assistant',
      name: 'Library Assistant',
      emoji: '📚',
      minAge: 14,
      salary: 2000,
      hoursPerWeek: 8,
      responsibilityRequired: 0,
      experienceRequired: 0,
      stressGain: 3,
      experienceGain: 3,
      customerSkillGain: 2,
    ),
    PartTimeJob(
      id: 'it_lab_monitor',
      name: 'IT Lab Monitor',
      emoji: '💻',
      minAge: 16,
      salary: 3500,
      hoursPerWeek: 12,
      responsibilityRequired: 60,
      experienceRequired: 0,
      stressGain: 4,
      experienceGain: 5,
      customerSkillGain: 2,
    ),
    PartTimeJob(
      id: 'burger_flipper',
      name: 'Burger Flipper',
      emoji: '🍔',
      minAge: 16,
      salary: 2800,
      hoursPerWeek: 12,
      responsibilityRequired: 0,
      experienceRequired: 0,
      stressGain: 7,
      experienceGain: 4,
      customerSkillGain: 3,
    ),
    PartTimeJob(
      id: 'food_runner',
      name: 'Food Runner',
      emoji: '🛵',
      minAge: 16,
      salary: 4000,
      hoursPerWeek: 20,
      responsibilityRequired: 20,
      experienceRequired: 5,
      stressGain: 9,
      experienceGain: 6,
      customerSkillGain: 3,
    ),
    PartTimeJob(
      id: 'bookstore_worker',
      name: 'Bookstore Worker',
      emoji: '📖',
      minAge: 14,
      salary: 2200,
      hoursPerWeek: 8,
      responsibilityRequired: 10,
      experienceRequired: 0,
      stressGain: 3,
      experienceGain: 4,
      customerSkillGain: 3,
    ),
    PartTimeJob(
      id: 'sports_shop_assistant',
      name: 'Sports Shop Assistant',
      emoji: '🏏',
      minAge: 15,
      salary: 2600,
      hoursPerWeek: 10,
      responsibilityRequired: 15,
      experienceRequired: 0,
      stressGain: 4,
      experienceGain: 4,
      customerSkillGain: 4,
    ),
    PartTimeJob(
      id: 'computer_shop_assistant',
      name: 'Computer Shop Assistant',
      emoji: '🖥️',
      minAge: 16,
      salary: 3800,
      hoursPerWeek: 14,
      responsibilityRequired: 45,
      experienceRequired: 15,
      stressGain: 5,
      experienceGain: 6,
      customerSkillGain: 3,
    ),
    PartTimeJob(
      id: 'tuition_helper',
      name: 'Tuition Helper',
      emoji: '✏️',
      minAge: 16,
      salary: 3000,
      hoursPerWeek: 8,
      responsibilityRequired: 40,
      experienceRequired: 10,
      stressGain: 4,
      experienceGain: 5,
      customerSkillGain: 2,
    ),
    PartTimeJob(
      id: 'movie_theatre_staff',
      name: 'Movie Theatre Staff',
      emoji: '🎬',
      minAge: 16,
      salary: 3000,
      hoursPerWeek: 12,
      responsibilityRequired: 20,
      experienceRequired: 5,
      stressGain: 5,
      experienceGain: 4,
      customerSkillGain: 5,
    ),
    PartTimeJob(
      id: 'pharmacy_helper',
      name: 'Pharmacy Helper',
      emoji: '💊',
      minAge: 17,
      salary: 3600,
      hoursPerWeek: 12,
      responsibilityRequired: 55,
      experienceRequired: 15,
      stressGain: 5,
      experienceGain: 5,
      customerSkillGain: 3,
    ),
    PartTimeJob(
      id: 'petrol_pump_attendant',
      name: 'Petrol Pump Attendant',
      emoji: '⛽',
      minAge: 18,
      salary: 4800,
      hoursPerWeek: 18,
      responsibilityRequired: 35,
      experienceRequired: 10,
      stressGain: 8,
      experienceGain: 6,
      customerSkillGain: 2,
    ),
    PartTimeJob(
      id: 'mall_kiosk_seller',
      name: 'Mall Kiosk Seller',
      emoji: '🧾',
      minAge: 16,
      salary: 3400,
      hoursPerWeek: 14,
      responsibilityRequired: 25,
      experienceRequired: 5,
      stressGain: 6,
      experienceGain: 5,
      customerSkillGain: 6,
    ),
    PartTimeJob(
      id: 'event_helper',
      name: 'Event Helper',
      emoji: '🎪',
      minAge: 16,
      salary: 4200,
      hoursPerWeek: 16,
      responsibilityRequired: 30,
      experienceRequired: 15,
      stressGain: 8,
      experienceGain: 6,
      customerSkillGain: 5,
    ),
    PartTimeJob(
      id: 'delivery_cyclist',
      name: 'Delivery Cyclist',
      emoji: '🚲',
      minAge: 17,
      salary: 4500,
      hoursPerWeek: 18,
      responsibilityRequired: 30,
      experienceRequired: 10,
      stressGain: 9,
      experienceGain: 6,
      customerSkillGain: 2,
    ),
    PartTimeJob(
      id: 'reception_desk_helper',
      name: 'Reception Desk Helper',
      emoji: '🛎️',
      minAge: 17,
      salary: 3700,
      hoursPerWeek: 14,
      responsibilityRequired: 45,
      experienceRequired: 20,
      stressGain: 5,
      experienceGain: 5,
      customerSkillGain: 7,
    ),
    PartTimeJob(
      id: 'print_shop_assistant',
      name: 'Print Shop Assistant',
      emoji: '🖨️',
      minAge: 16,
      salary: 3100,
      hoursPerWeek: 12,
      responsibilityRequired: 25,
      experienceRequired: 5,
      stressGain: 4,
      experienceGain: 5,
      customerSkillGain: 3,
    ),
    PartTimeJob(
      id: 'clinic_front_desk',
      name: 'Clinic Front Desk',
      emoji: '🏥',
      minAge: 18,
      salary: 5200,
      hoursPerWeek: 18,
      responsibilityRequired: 65,
      experienceRequired: 25,
      stressGain: 7,
      experienceGain: 7,
      customerSkillGain: 6,
    ),
    PartTimeJob(
      id: 'junior_sales_promoter',
      name: 'Junior Sales Promoter',
      emoji: '📣',
      minAge: 16,
      salary: 3900,
      hoursPerWeek: 16,
      responsibilityRequired: 20,
      experienceRequired: 10,
      stressGain: 7,
      experienceGain: 5,
      customerSkillGain: 8,
    ),
  ];

  static PartTimeJob? findById(String id) {
    for (final job in jobs) {
      if (job.id == id) return job;
    }
    return null;
  }

  static String? lockReason(PartTimeJob job, Character character) {
    if (character.age < job.minAge) return 'Requires Age ${job.minAge}+';
    if (character.partTimeResponsibility < job.responsibilityRequired) {
      return 'Requires Responsibility ${job.responsibilityRequired}+';
    }
    if (character.partTimeExperience < job.experienceRequired) {
      return 'Requires Experience ${job.experienceRequired}+';
    }
    return null;
  }
}
